[Translation] [russian] - context.article
ardanlabs/gotour pull request #225
Opened 2024-01-20 15:16 UTC by alexshd

2024-01-20 20:45 UTC, alexshd commented on _content/tour/rus/context.article
> +"Значения контекста предназначены для данных, копируемых по запросу, которые проходят через программы в
After being stuck on translating this sentence for too long ... Gave it to ChatGPT ...
This word collection has no meaning or is very far from the origin...

HELP Please... :)

2024-01-24 19:33 UTC, rumyantseva reviewed
This one is hard. I started reviewing, but I don't really like my suggestions. I need to think more.

2024-01-24 19:33 UTC, rumyantseva commented on _content/tour/rus/context.article
> +   Пакет Context
```suggestion
Пакет Context
```

2024-01-24 19:33 UTC, rumyantseva commented on _content/tour/rus/context.article
> +Пакет context определяет тип `Context`, который переносит сроки, сигналы отмены и другие значения, связанные с запросами, через границы API и между процессами.
```suggestion
Пакет context определяет тип `Context`, который включает работу со сроками (дедайнами), сигналами отмены и другими значениями, имеющими смысл в рамках запросов API и между процессами.
```

2024-01-24 19:33 UTC, rumyantseva commented on _content/tour/rus/context.article
> +Значения контекста (`ctx.Value()`) предназначены для данных, скопированных на запрос, которые передаются через программы в распределенной системе.
```suggestion
Значения Context предназначены для работы с данными из области действия запросов передающихся через программы в распределенных системах.
```

2024-04-29 02:44 UTC, shalimski requested changes

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Этот метод позволяет обновлять поле `Context` значения `Request`. В строке 26,
```suggestion
Этот метод позволяет обновлять поле `Context` внутри `Request`. В строке 26,
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +сделанные во время обработки запроса или действия, распространялись и соблюдались.
```suggestion
Это важное правило, поскольку контекст основан на запросах или действиях. Вы хотите, чтобы контекст и любые изменения, внесенные в него во время обработки запроса или задачи, распространялись и соблюдались.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +На этом фрагменте кода видно функцию-обработчик с именем `List`,
```suggestion
В этом фрагменте кода видно функцию с именем `List`,
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +которая выполняется при запросе пользователя через `HTTP` для данной конечной точки.
```suggestion
которая выполняется, когда пользователь отправляет HTTP-запрос для этой конечной точки.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Обработчик принимает контекст (Context) в качестве первого параметра,
```suggestion
Обработчик принимает контекст `Context` в качестве первого параметра,
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +поскольку он является частью запроса и выполняет ввод-вывод.
```suggestion
поскольку он является частью запроса и будет выполнять операции ввода-вывода.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Как видно на строках 25, 28 и 33, тот же самый контекст (Context) передается вниз по стеку вызовов.
```suggestion
Как видно на строках 25, 28 и 33, тот же самый контекст `Context` передается вниз по стеку вызовов.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Новый объект контекста (Context) не создается, поскольку для этой функции не требуются изменения.
```suggestion
Новый объект контекста не создается, так как эта функция не требует его изменения.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +связанного с этим запросом, была бы утеряна. Это не то, что вам нужно.
```suggestion
Если бы эта функция создала новое значение контекста верхнего уровня, любая существующая контекстная информация из вызова более высокого уровня, связанная с этим запросом, была бы потеряна. Это не то, что вам нужно.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +эта функция должна уважать любую информацию о тайм-ауте, установленную в контексте предыдущим пользователем.
```suggestion
эта функция должна учитывать любую информацию о тайм-ауте, установленную в контексте любого вызывающего объекта выше.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +*Получает* *контекст* *с* *помощью* *WithCancel*, *WithDeadline*, *WithTimeout* *или* *WithValue*.
```suggestion
*Замена* *контекста* *с* *помощью* *WithCancel*, *WithDeadline*, *WithTimeout* *или* *WithValue*.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Это небольшая программа, демонстрирующая семантическую природу значения функции `WithTimeout`.
```suggestion
Это небольшая программа, которая показывает семантическую природу функции `WithTimeout`. 
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +цепочке вызовов требуется определенный таймаут или крайний срок, они также должны использовать соответствующую функцию `With`
```suggestion
цепочке вызовов потребуется свой собственный определенный таймаут или крайний срок, они также должны использовать соответствующую функцию `With` 
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Крайне важно, чтобы любая функция отмены, возвращаемая функцией `With`, была выполнена до возврата функции.
```suggestion
Крайне важно, чтобы любая функция отмены, возвращаемая функцией `With`, выполнялась до того, как эта функция вернет результат.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +*Когда* *контекст* *удаляется*, *все* *производные* *от* *него* *контексты* *также* *удаляются*.
```suggestion
*Когда* *контекст* *отменяется*, *все* *производные* *от* *него* *контексты* *также* *отменяются*.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +что есть у родительского `Context`, плюс все новые модификации. Это означает, что если родительский Контекст удаляется,
```suggestion
что есть у родительского `Context`, плюс любые новые изменения. Это означает, что если родительский Контекст отменяется, 
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +то удаляются и все дочерние Контексты, производные от этого родительского Контекста.
```suggestion
то отменяются и все дочерние Контексты, производные от этого родительского Контекста.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +не будет очищен.
```suggestion
не будет отменен.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +В строке 28 главная горутина очищает свое значение `Context`, а затем в строке 29 ждет, пока все десять горутин получат сигнал,
```suggestion
В строке 28 главная горутина отменяет свой  `Context`, а затем в строке 29 ждет, пока все десять горутин получат сигнал,
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Не передавайте контекст `nil`, даже если функция это позволяет. Передавайте контекст `TODO`, если вы не уверены,
```suggestion
Не передавайте в контекст значение `nil`, даже если функция это позволяет. Передавайте контекст `TODO`, если вы не уверены, 
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Вы никогда не знаете всего, пока пишете код, но, надеюсь, вы знаете достаточно, чтобы двигаться вперед.
```suggestion
Вы никогда не знаете всего, пока пишете код, но, надеюсь, вы знаете достаточно, чтобы продвигаться вперед. 
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +*Используйте* *значения* *с* *Context* *только* *в* *области* *действия* *запроса* *данных*.
```suggestion
*Используйте* *значения* *Context* *только* *для* *данных,* *относящихся* *к* *области* *запроса.*
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Передавайте данные как параметр функции Это самый очевидный способ перемещения данных в программу, не скрывая их.
```suggestion
Передавайте данные как параметр функции. Это самый очевидный способ перемещения данных в программу, не скрывая их.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +*Отладочные* *или* *трассировочные* *данные* *безопасно* *передавать* *с* *Context*.
```suggestion
*Отладочные* *или* *трассировочные* *данные* *безопасно* *передавать* *через* *Context*.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Данные, которые могут быть сохранены и получены значением Context, являются отладочной и трассировочной информацией.
```suggestion
Данные, которые могут быть сохранены и получены из контекста, могут являтся отладочной и трассировочной информацией.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Посмотрите, как тип Values создается в строке 86, а затем хранится в Context в строке 90.
```suggestion
Посмотрите, как тип Values создается в строке 86, а затем сохраняется внутри Context в строке 90. 
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +Последствия передачи информации через Context показаны в коде на
```suggestion
Результат передачи информации через контекст  показан в коде на
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +- Замените Context с помощью `WithCancel`, `WithDeadline`, `WithTimeout` или `WithValue`.
```suggestion
- Заменяйте Context с помощью `WithCancel`, `WithDeadline`, `WithTimeout` или `WithValue`.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +- Не храните `Context` внутри  `struct`; вместо этого передавайте `Context` явно каждой функции, которой он нужен.
```suggestion
- Не храните `Context` внутри структур, вместо этого передавайте `Context` явно каждой функции, которой он нужен.
```

2024-04-29 02:44 UTC, shalimski commented on _content/tour/rus/context.article
> +- Не передавайте Context с нулевым значением, даже если функция это допускает. Передавайте `context.TODO`, если вы не уверены в том, какой Context использовать.
```suggestion
- Не передавайте вместо Context значение `nil`, даже если функция это допускает. Передавайте `context.TODO`, если вы не уверены в том, какой Context использовать.
```

2024-04-29 20:47 UTC, merged